import { sanitizeBranchPart, toSafeText } from './common.js'

const createBranchEntropySuffix = () => Math.random().toString(36).slice(2, 6)

const isAutoGeneratedHeadBranch = value => {
  const branch = sanitizeBranchPart(value)
  if (!branch) {
    return false
  }

  return /^feat\/component-[a-z0-9]{4}(?:-\d+)?$/.test(branch)
}

const createDefaultBranchName = () => {
  const entropy = createBranchEntropySuffix()
  return `feat/component-${entropy}`
}

const toBranchCacheKey = repository => {
  const owner = toSafeText(repository?.owner)
  const name = toSafeText(repository?.name)
  if (!owner || !name) {
    return ''
  }

  return `${owner}/${name}`
}

const createSelectOption = ({ value, label, selected = false, disabled = false }) => {
  const option = document.createElement('option')
  option.value = value
  option.textContent = label
  option.selected = selected
  option.disabled = disabled
  return option
}

const mergeBranchOptions = ({ preferredBranch, branchNames }) => {
  const dedupe = new Set()
  const result = []

  const pushBranch = branch => {
    const safeBranch = toSafeText(branch)
    if (!safeBranch || dedupe.has(safeBranch)) {
      return
    }

    dedupe.add(safeBranch)
    result.push(safeBranch)
  }

  pushBranch(preferredBranch)

  if (Array.isArray(branchNames)) {
    for (const branchName of branchNames) {
      pushBranch(branchName)
    }
  }

  return result
}

export {
  createDefaultBranchName,
  createSelectOption,
  isAutoGeneratedHeadBranch,
  mergeBranchOptions,
  toBranchCacheKey,
}
