import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { cdnImportSpecs } from '../src/modules/cdn.js'

const validPrimaryCdns = new Set(['importMap', 'esm', 'jspmGa'])

const parsePrimaryCdnFromArgs = argv => {
  for (const arg of argv) {
    if (!arg.startsWith('--primary-cdn=')) continue
    const value = arg.slice('--primary-cdn='.length)
    return value || null
  }
  return null
}

const resolvePrimaryCdn = () => {
  const fromArgs = parsePrimaryCdnFromArgs(process.argv.slice(2))
  const fromEnv = process.env.KNIGHTED_PRIMARY_CDN
  const selected = fromArgs ?? fromEnv ?? 'importMap'

  if (!validPrimaryCdns.has(selected)) {
    throw new Error(
      `Invalid primary CDN: ${selected}. Expected one of importMap, esm, jspmGa.`,
    )
  }

  return selected
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(__dirname, '..')
const srcDir = resolve(projectRoot, 'src')
const distDir = resolve(projectRoot, 'dist')
const distIndexHtml = resolve(distDir, 'index.html')
const distProdImportsFile = resolve(distDir, 'prod-imports.js')

const primaryCdn = resolvePrimaryCdn()

const productionRuntimeScript = `<script>window.__KNIGHTED_PRIMARY_CDN__ = "${primaryCdn}"</script>`

const createProdImportsModule = async () => {
  const specifiers = [
    ...new Set(
      Object.values(cdnImportSpecs)
        .map(spec => spec?.importMap)
        .filter(specifier => typeof specifier === 'string' && specifier.length > 0),
    ),
  ]

  if (specifiers.length === 0) {
    throw new Error(
      'No importMap specifiers found in src/modules/cdn.js (cdnImportSpecs).',
    )
  }

  const lines = [
    '/*',
    ' * Generated by scripts/build-prepare.js from src/modules/cdn.js (cdnImportSpecs).',
    ' * JSPM links this module to trace top-level production imports.',
    ' */',
    ...specifiers.map(specifier => `import '${specifier}'`),
    '',
  ]

  await writeFile(distProdImportsFile, lines.join('\n'))
}

await rm(distDir, { recursive: true, force: true })
await mkdir(distDir, { recursive: true })
await cp(srcDir, distDir, { recursive: true })
await createProdImportsModule()

const html = await readFile(distIndexHtml, 'utf8')

if (!html.includes(productionRuntimeScript)) {
  const bootstrapModuleScriptRegex =
    /<script\b(?=[^>]*\btype=(['"])module\1)(?=[^>]*\bsrc=(['"])bootstrap\.js\2)[^>]*>\s*<\/script>/i
  const updatedHtml = html.replace(
    bootstrapModuleScriptRegex,
    match => `${productionRuntimeScript}\n    ${match}`,
  )

  if (updatedHtml === html) {
    throw new Error('Could not locate bootstrap module script tag in dist/index.html.')
  }

  await writeFile(distIndexHtml, updatedHtml)
}
